### ISSUE TITLE
Rest-Client related error with Fastlane 2.58

### ISSUE THREAD

**Issue by paulryanclark** [justinsinger/fastlane_plugins#5]
Because of changes in dependencies when updating to Fastlane 2.58 I am pinned to rest-client 1.6.7. This version produces an error. Any help would be great. Thank you. 

```
ERROR [2017-09-20 16:08:33.68]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `[]' for Set: {#<MIME::Type

URL: https://api.github.com/search/issues?q=undefined%20method%20%60[]'%20for%20Set:%20%7B%23%3CMIME::Type+repo:fastlane/fastlane
➡️  set_trade_representative_contact_information: undefined method `chomp' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/9140 [closed] 4 💬
    5 weeks ago

➡️  undefined method `[]' for nil:NilClass (NoMethodError)
    https://github.com/fastlane/fastlane/issues/9087 [closed] 2 💬
    03 Aug 2017

➡️  Undefined method 'add_external_tester!'
    https://github.com/fastlane/fastlane/issues/8940 [closed] 3 💬
    24 Jul 2017

and 46 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60[]%27%20for%20Set:%20%7B%23%3CMIME::Type&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/runner/.rvm/gems/ruby-2.3.3/gems/rest-client-1.6.7/lib/restclient/request.rb:307:in `type_for_extension': [!] undefined method `[]' for #<Set: {#<MIME::Type: application/json>}> (NoMethodError)
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/rest-client-1.6.7/lib/restclient/request.rb:312:in `type_for_extension'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/rest-client-1.6.7/lib/restclient/request.rb:286:in `block (2 levels) in stringify_headers'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/rest-client-1.6.7/lib/restclient/request.rb:286:in `map'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/rest-client-1.6.7/lib/restclient/request.rb:286:in `block in stringify_headers'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/rest-client-1.6.7/lib/restclient/request.rb:272:in `each'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/rest-client-1.6.7/lib/restclient/request.rb:272:in `inject'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/rest-client-1.6.7/lib/restclient/request.rb:272:in `stringify_headers'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/rest-client-1.6.7/lib/restclient/request.rb:92:in `make_headers'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/rest-client-1.6.7/lib/restclient/request.rb:58:in `initialize'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `new'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/rest-client-1.6.7/lib/restclient.rb:72:in `post'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-plugin-github_job_status-0.2.1/lib/fastlane/plugin/github_job_status/actions/github_job_status_action.rb:38:in `post'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-plugin-github_job_status-0.2.1/lib/fastlane/plugin/github_job_status/actions/github_job_status_action.rb:29:in `run'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-2.58.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-2.58.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-2.58.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-2.58.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-2.58.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-2.58.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-2.58.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:50:in `block (2 levels) in parsing_binding'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-2.58.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-2.58.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-2.58.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-2.58.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-2.58.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-2.58.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-2.58.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-2.58.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-2.58.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-2.58.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-2.58.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/runner/.rvm/gems/ruby-2.3.3/gems/fastlane-2.58.0/bin/fastlane:20:in `<top (required)>'
	from /Users/runner/.rvm/gems/ruby-2.3.3/bin/fastlane:22:in `load'
	from /Users/runner/.rvm/gems/ruby-2.3.3/bin/fastlane:22:in `<main>'
	from /Users/runner/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/runner/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
ERROR: Job failed: exit status 1
```

**Comment by lyndsey-ferguson** [comment]
💢 I'm having the same issue!

**Comment by justinsinger** [comment]
@paulryanclark It's updated now and version 0.2.2 is released, sorry I didn't see this issue until now!

**Comment by justinsinger** [comment]
@paulryanclark And now version 0.2.3 is released which actually fixes it, so use that one
